
import { Word, WordGroup } from './types';

// Compressed data format: "Term|Meaning" to save space while including all words
const compressedData = [
"Abacus|Frame with ball for calculating",
"Abate|To lessen to subside",
"Abdication|Giving up control authority",
"Aberration|Straying away from that is normal",
"Abet|Help/encourage somebody (in doing wrong)",
"Abeyance|Suspended action",
"Abhor|To hate to detest",
"Abide|To faithful to endure",
"Abjure|Promise or swear to give up",
"Abraded|Rubbed off worn away by friction",
"Abrogate|Repeal or annul by authority",
"Abscond|To go away suddenly (to avoid arrest)",
"Abstruse|Difficult to comprehend obscure",
"Abut|Border on",
"Abysmal|Bottomless extreme",
"Acarpous|Sterile, no longer fertile",
"Acclaimed|Welcomed with shouts and approval",
"Accolade|Praise approval",
"Accretion|The growing of separate things into one",
"Adamant|Kind of stone inflexible",
"Admonitory|Containing warning",
"Adorn|Add beauty decorate",
"Adulteration|Making impure, poorer in quality",
"Affable|Polite and friendly",
"Affinity|Close connection/relationship",
"Aggravate|Make worse irritate",
"Agile|Active quick moving",
"Agog|Eager/excited",
"Ail|Trouble be ill",
"Alacrity|Eager and cheerful readiness",
"Alcove|Recess/partially enclose place",
"Allegiance|Duty support loyalty",
"Alleviate|Make (pain) easier to bear",
"Alloy|To debase by mixing with something inferior",
"Aloof|Reserved indifferent",
"Amalgamate|Mix combine unite societies",
"Ambidextrous|Able to use the left hand or the right equally well",
"Ambiguous|Doubtful uncertain",
"Ambivalent|Having both of two contrary meanings",
"Ameliorate|Improve make better",
"Amortize|End (a debt) by setting aside money",
"Anguish|Severe suffering",
"Animosity|Strong dislike",
"Antidote|Medicine used against a poison or a disease",
"Antithetical|Direct opposing",
"Apartheid|Brutal racial discrimination",
"Aplomb|Self-confidence",
"Apostate|One who abandons long-held religious or political convictions",
"Apotheosis|Deification glorification to godliness",
"Appease|Make quiet or calm",
"Apprehensive|Grasping understanding fear unhappy feeling about future",
"Apprise|Give notice to inform",
"Approbation|Approval",
"Apropos|Appropriate to the situation apt",
"Apt|Well-suited quick-witted",
"Arabesque|A complex ornate design",
"Arboreal|Of connected with trees",
"Ardor|Enthusiasm",
"Arduous|Steep difficult ascent laborious",
"Argot|Jargon slang",
"Arrant|In the highest degree",
"Arrogance|Proud superior manner of behavior",
"Articulate|Speak distinctly connect by joints",
"Ascend|Go or come up",
"Ascertain|Get to know",
"Ascetic|Practicing self-denial austere stark",
"Ascribe|Consider to be the origin of or belonging to",
"Aseptic|Surgically clean",
"Asperity|Roughness harshness ill temper irritability",
"Aspersion|Slander",
"Assail|With attack violently",
"Assiduous|Diligent hard-working sedulous",
"Assuage|Make something (pain desire) less",
"Asterisk|The mark * (e.g. omitted letters)",
"Astringent|Substance that shrinks",
"Astute|Clever quick at seeing to get an advantage",
"Atonement|Repayment death of Jesus",
"Attenuate|Make thin, weaken enervate",
"Attune|Bring into harmony",
"Audacious|Daring foolishly bold impudent",
"Augury|Omen sign",
"August|Majestic venerable",
"Auspicious|Favorable successful prosperous",
"Austere|Severely moral and strict simple and plain",
"Auxiliary|Helping supporting",
"Aver|Affirm assert prove justify",
"Aversion|Strong dislike",
"Avid|Eager greedy",
"Avow|Admit declare openly",
"Baleful|Harmful, ominous causing evil",
"Balk|Obstacle purposely to get on the way of",
"Baneful|Causing harm or ruin pernicious destructive",
"Barrage|Artificial obstacle built across a river",
"Barren|Not good enough unable to have young ones without value",
"Bask|In enjoy warmth and light",
"Beatify|To bless make happy or ascribe a virtue to",
"Bedizen|To adorn especially in a cheap showy manner",
"Belabor|Beat hard",
"Bellicose|Belligerent pugnacious warlike",
"Belligerent|(Person nation) waging war",
"Benefactor|Person who has given help",
"Benevolence|Wish or activity in doing good",
"Benign|Kind and gentle mild (climate)",
"Bequest|Arrangement to give something at death",
"Berate|Scold sharply",
"Bereft|Rob or dispossess of something (material)",
"Bewilder|Puzzle confuse",
"Bigot|Stubborn narrow-minded person",
"Bilge|Bulge the protuberance of a cask",
"Blandishment|Flattery coaxing",
"Blandness|Polite manner comforting uninteresting",
"Blatant|Noisy and rough",
"Blithe|Cheerful casual carefree",
"Bogus|Sham counterfeit not genuine",
"Boisterous|Loud noisy rough lacking restraint",
"Bolster|Give greatly needed support",
"Boorish|Crude offensive rude",
"Brash|Hasty rush cheeky saucy",
"Brass|Yellow metal (mixing copper and zinc)",
"Brazen|Made of brass",
"Breach|Opening broken place breaking",
"Brittle|Easily broken",
"Broach|Bring up announce begin to talk about",
"Brook|To tolerate endure",
"Buoyant|Able to float light-hearted",
"Burgeon|Grow forth send out buds",
"Burnish|To polish rub to a shine",
"Cabal|A scheme or plot a group of plotters",
"Cadge|To beg to get by begging",
"Cajole|Use flattery or deceit to persuade",
"Calipers|Metal supports attached to the legs measuring instrument",
"Calumny|Slander aspersion",
"Candid|Frank straight-forward",
"Cant|Insincere talk/jargon",
"Cantankerous|Bad-tempered/quarrelsome",
"Canvass|Discuss thoroughly sort of touting",
"Castigate|To chastise correct by punishing",
"Castigation|Severe punishment",
"Catalyst|Substance that causes speeding up",
"Caustic|Biting sarcastic",
"Censure|Expression of blame or disapproval a rebuke",
"Centurion|Leader of a unit of 100 soldiers",
"Chary|Cautious wary",
"Chastened|Corrected punished",
"Chastisement|Punishment",
"Chauvinist|A blindly devoted patriot",
"Chicanery|Legal trickery/false argument",
"Chisel|Steel tool for shaping material",
"Churl|Bad-tempered person",
"Clamor|Shout complain with a lot of noise",
"Clientele|Customers",
"Clinch|Come to grips/settle conclusively",
"Cling|To resist separation",
"Clot|Half-solid lump formed from liquid",
"Cloture|Closing device (in parliament) to end a debate by voting",
"Coagulation|Change to a thick and solid state",
"Coalescing|Coming together and uniting into one substance",
"Coax|Get somebody to do something by kindness",
"Coda|Passage that completes a piece of music",
"Coddle|Treat with care and tenderness",
"Coerce|Compel to force to make obedient",
"Coeval|Of the same period coexisting",
"Cogent|Strong convincing",
"Cogitate|Think deeply mediate",
"Cognizant|Being fully aware of",
"Colander|Bowl-shaped vessel with many holes used to drain on water",
"Collusion|Secret agreement for a deceitful purpose",
"Combustion|Process of burning",
"Commemorate|Keep the memory of",
"Commodious|Having plenty of space for what is needed",
"Commuter|Person who travels regularly",
"Complaisance|Tending to comply obliging willingness to please",
"Compunction|Feeling of regret for one's action",
"Conceal|Hide keep secret",
"Conceit|Over-high opinion of too much pride",
"Conciliatory|Reconciling soothing comforting mollifying",
"Concord|Agreement or harmony",
"Concur|Agree in opinion happen together",
"Condense|Increase in density strength make laconic",
"Condone|Forgive",
"Congeal|Make or become stiff and solid",
"Conjoin|To join together",
"Connoisseur|A person with good judgement (e.g. in art)",
"Connotation|Suggestion in addition to",
"Consequential|Pompous, self important",
"Console|Give comfort or sympathy to",
"Conspicuous|Easily seen remarkable",
"Consternation|Surprise and fear dismay",
"Constrain|Compel",
"Constrict|Make tight or smaller",
"Consume|Get to the end of",
"Consummate|Perfect/make perfect/complete",
"Contemn|To scorn or despise",
"Contentious|Argumentative pugnacious combative quarrelsome",
"Contiguous|Touching neighboring near",
"Contrite|Filled with deep sorrow for wrongdoing",
"Contumacious|Insubordinate rebellious",
"Conundrum|A riddle dilemma enigma",
"Conviction|Convincing firm belief",
"Convoke|Call together summon",
"Convoluted|Complicated coiled twisted",
"Cordial|Warm and sincere",
"Cordon|Line (of police acting as a guard)",
"Cornucopia|Abundant supply",
"Corporeal|Physical of or for the body",
"Correlate|Have a mutual relation",
"Corroboration|Additional strengthening evidence",
"Countenance|To favor or approve of",
"Counterfeit|Forgery",
"Countervail|Counterbalance",
"Covert|Disguised",
"Covetous|Eagerly desirous",
"Cower|Crouch shrink back",
"Coy|Shy/modest (esp. of a girl)",
"Crass|Very great (esp. stupidity)",
"Cravat|Piece of linen worn as a necktie",
"Craven|Cowardly",
"Crease|Line made by crushing white line on the ground in cricket",
"Credulity|Too great a readiness to believe things",
"Credulous|Ready to believe things",
"Crush|Press lose shape subdue overwhelm",
"Cryptic|Secret with a hidden meaning",
"Cumbersome|Burdensome heavy and awkward to carry",
"Curmudgeon|Bad-tempered person",
"Curriculum|Course of study",
"Cursory|Quick hurried",
"Curtail|Make shorter then was planned",
"Dainty|Pretty/delicate(food)/difficult to please",
"Daunt|Intimidate make fearful",
"Dawdler|Person who is slow waste of time",
"Dearth|Shortage",
"Debacle|A breakup overthrow sudden disaster",
"Decorum|Propriety properness",
"Decree|Order given by authority",
"Decry|Disapprove of",
"Defer|Postpone give way (to show respect)",
"Deferential|Showing respect",
"Defiance|Open disobedience or resistance",
"Delineate|To portray depict sketch out",
"Deluge|Great flood heavy rush of water",
"Demagogue|Person appealing not to reasons",
"Demur|To hesitate raise objections",
"Denigrate|Blacken belittle sully defame",
"Denouement|An outcome or solution the unraveling of a plot",
"Deplete|Use until none remains",
"Deposition|Dethronement depositing",
"Deprave|Make morally bad corrupt",
"Deprecate|Protest against express disapproval of",
"Dereliction|Deserting and leaving to tall into ruins",
"Derision|Ridicule mockery deriding",
"Derivative|Unoriginal obtained from another source",
"Derogatory|Insulting tending to damage",
"Descry|Catch sight of see something in the distance",
"Desiccant|Substance used to absorb moisture",
"Desuetude|Cessation of use disuse",
"Desultory|Aimless haphazard digressing at random",
"Deter|Discourage hinder",
"Detraction|Slandering verbal attack aspersion",
"Detumescence|Diminishing or lessening of swelling",
"Deviance|Being different in moral standards (from normal)",
"Dexterity|Skill (esp. in handling)",
"Diaphanous|Transparent gauzy",
"Diatribe|Bitter and violent attack in words",
"Diffidence|Shyness",
"Dilate|Speak comprehensively become wider large",
"Disallow|Refuse to allow or accept as a correct",
"Discern|See with an effort but clearly",
"Discomfit|Confuse embarrass",
"Disconcert|Upset the self-possession of",
"Discountenance|Refuse to approve of",
"Discourse|Speech lecture",
"Discredit|Refuse to believe",
"Discreet|Careful/prudent",
"Discrete|Individually distinct",
"Disdain|Look on with contempt",
"Disencumber|Free from encumbrance",
"Disheveled|Untidy",
"Disingenuous|Sophisticated artful trying to deceive cunning",
"Disinter|Dig up from the earth",
"Dislodge|Move force from the place occupied",
"Dismal|Sad gloomy miserable",
"Disparate|Essentially different",
"Disproof|Proof to the contrary",
"Dissemble|Speak or behave so as to hide something (in mind)",
"Disseminate|Distribute (esp. ideas)",
"Dissent|Have a different opinion refuse to assent",
"Dissolution|Disintegration looseness in morals",
"Distraught|Distracted violently upset in mind",
"Divergence|Getting farther apart from a point",
"Divestiture|Taking oft getting rid of giving up",
"Divulge|Make known something secret",
"Doggerel|Trivial poorly constructed verse",
"Dogmatic|Positive certain arbitrary without room for discussion",
"Dolt|Stupid fellow",
"Dormant|In a state of inactivity but awaiting development",
"Dote|Show much fondness center one's attention",
"Drawl|Slow way of speaking",
"Droll|Jesting",
"Drone|Male bee person who isn't self-employed",
"Drowsiness|Feeling sleepy half asleep",
"Dubious|Reeling doubt",
"Dud|No use person something that fails",
"Dulcet|Melodious harmonious",
"Dupe|Cheat make a fool of",
"Duplicity|Deliberate deception",
"Duress|Threats to compel somebody",
"Dwarf|Person or somebody much below the usual size",
"Dynamo|A generator something that produces electric current",
"Earthenware|Dishes made of baked clay",
"Ebullience|Exuberance outburst of feeling",
"Ebullient|Overflowing with enthusiasm showing excitement",
"Ecumenical|Representing the whole Christian world",
"Edacious|Voracious devouring",
"Eddy|Circular or spiral movement (e.g. of wind)",
"Edible|Fit to be eaten/not poisonous",
"Effete|Infertile worn out weak",
"Efficacy|Production of a desired result",
"Effluvia|Outflow in a stream of particles a noxious odor or vapor",
"Effrontery|Boldness impudence arrogance",
"Egress|Way out exit",
"Elaborate|Worked out with much care in great detail",
"Elegy|A lament a melancholy composition",
"Elicit|Draw out",
"Eloquence|Fluent speaking skillful use of language",
"Emaciate|Make thin and weak",
"Embellish|Make beautiful",
"Embezzle|Use in a wrong way for one's own benefit",
"Emote|Stir up excite",
"Empirical|Relying on experiment",
"Encapsulate|Enclose in capsule",
"Encomium|Warm or glowing praise eulogy panegyric",
"Encumbrance|Burden things that get on the way of",
"Endearing|Making dear or liked",
"Endemic|Epidemic",
"Endorse|Write one's name on the back of",
"Enduring|Lasting",
"Enervate|Weaken deprive of strength attenuate",
"Engender|Cause produce give rise to",
"Engrave|Impress deeply",
"Engrossing|Taken up all the time or attention writing in large or formal",
"Engulf|Swallow up",
"Enigma|Something that is puzzling",
"Enmity|Hatred being an enemy",
"Ensign|Flag/badge",
"Entangle|Put into difficulties",
"Enthral|Please greatly/enslave (fig)",
"Entice|Tempt or persuade",
"Entreat|Ask earnestly",
"Enunciate|Pronounce (words)/express a theory",
"Enzyme|Catalyst",
"Epicurean|Devoted to pleasure (sensuous enjoyment)",
"Epistle|Letter",
"Epithet|Adjective",
"Epitome|Brief summary representative example a typical model",
"Equable|Steady regular",
"Equanimity|Calmness of temperament",
"Equilibrium|State of being balanced",
"Equipoise|Equal distribution of weight equilibrium",
"Equivocal|Having a double or doubtful meaning suspicious",
"Equivocate|Try to deceive by equivocal language",
"Eradicate|Get rid of pull up by the roots",
"Erratic|Irregular in behavior or opinion",
"Eschew|Avoid",
"Esoteric|Abstruse intended only for a small circle of",
"Espouse|Marry give one's support to",
"Eulogy|Formal praise panegyric",
"Euphoria|Elation state of pleasant excitement",
"Euthanasia|Easy and painless death",
"Evasive|Tending to evade",
"Evince|To show clearly to indicate",
"Evoke|Call up bring out",
"Excoriation|Severe criticism",
"Exculpate|To clear from a charge of guilt",
"Exhaustive|Complete thorough",
"Exigency|Emergency an urgent situation",
"Exoneration|Set somebody clear free (e.g. from blame)",
"Exorbitant|Much too high or great",
"Expatiate|To roam wander freely",
"Expedient|Likely to be useful for a purpose",
"Expiation|Ending expiring",
"Exploit|Brilliant achievement develop use selfishly",
"Expostulate|Argue earnestly to dissuade correct or protest",
"Expurgate|To remove obscenity purify censor",
"Exscind|To cut out cut away",
"Extant|Still in existence",
"Extempore|Without previous thought or preparation",
"Extenuate|Reduce the strength of lessen seriousness partially excuse",
"Extinct|No longer active",
"Extinguish|End the existence of wipe or put out",
"Extirpate|To destroy exterminate cut out exscind",
"Extol|Praise highly",
"Extort|Obtain by threats violence",
"Extralegal|Outside the law",
"Extricable|That can be freed",
"Extrovert|Cheerful person",
"Exuberance|State to growing vigorously being full of life",
"Facetious|Humorous funny jocular",
"Facile|Easily done",
"Fallacious|Based on error",
"Falter|Waver/move in an uncertain manner",
"Fatuous|Without sense foolish self-satisfaction",
"Fawn|Young deer try to win somebody's favor",
"Feckless|Lacking purpose or vitality ineffective careless",
"Fecund|Fertile",
"Feint|Pretend",
"Felicitous|Suited to the circumstances, well chosen",
"Felon|Person guilty of murder",
"Ferment|Substance become excited",
"Ferocity|Savage cruelty",
"Ferret|Discover by searching",
"Fervid|Showing earnest feeling",
"Fervor|Warmth of feelings, earnestness",
"Fetid|Stinking",
"Fetter|To shackle, put in chains",
"Feud|Bitter quarrel over a long period of time",
"Fidelity|Loyalty",
"Fidget|Move restlessly, make nervous",
"Figurehead|Carved image on the prow of a ship",
"Finesse|Delicate way of dealing with a situation",
"Finical|Too fussy about food clothing etc.",
"Finicky|Finical",
"Fission|Spitting or division (esp. of cells)",
"Fixate|Stare at",
"Flak|Criticism/anti-aircraft quos",
"Flamboyant|Brightly colored florid",
"Flaunting|Show off complacently",
"Flax|Pale yellow (hair) a plant",
"Fledged|Able to fly trained experienced",
"Fleet|Number of ships quick-moving",
"Flinch|Draw move back wince",
"Flop|Fail/move/rail clumsily",
"Florid|Very much ornamented naturally red (e.g. of face)",
"Flout|Reject mock to go against (as in going against tradition)",
"Fluke|Lucky stroke",
"Fluster|Make nervous or confused",
"Foible|Defect of character (a person is wrongly proud)",
"Foil|Prevent from carrying out contrast",
"Foment|Put something warm (to lessen the pain)",
"Foolproof|Incapable of failure or error",
"Foppish|Like a man who pays too much attention to his clothes",
"Forage|Food for horses and cattle",
"Forbear|Refrain from be patient ancestor",
"Forbearance|Patience willingness to wait",
"Ford|Shallow place in a river (to cross)",
"Forestall|Prevent by taking action in advance preempt",
"Forfeit|Suffer the loss of something",
"Forge|Workshop for the shaping of metal to shape metal lead",
"Forgery|Counterfeit",
"Forswear|Renounce disallow repudiate",
"Foster|Nurture care for",
"Fracas|Noisy quarrel",
"Fragile|Easily injured broken or destroyed",
"Fragrant|Sweet-smelling",
"Frantic|Wildly excited with joy pain anxiety",
"Frenetic|Frantic frenzied",
"Fret|Worry irritation wear away",
"Fringe|Edge ornamental part of hair over the forehead",
"Froward|Intractable not willing to yield or comply stubborn",
"Frugal|Careful economical",
"Fulmination|Bitter protest",
"Fulsome|Disgusting offensive due to excessiveness",
"Gainsay|To deny to oppose",
"Garble|Make unfair selection from facts",
"Garment|Article of clothing",
"Garner|To gather and save to store up",
"Garrulity|Talkativeness",
"Garrulous|Too talkative",
"Gaucherie|Socially awkward tactless behavior",
"Germane|Relevant, pertinent to",
"Gist|The point general sense",
"Glean|Gather facts in small quantities",
"Glib|Ready and smooth but not sincere",
"Glimmer|Weak/unsteady light",
"Gloat|Over look at with selfish delight",
"Glut|Supply to much fill to excess",
"Gnaw|Waste away bite steadily",
"Goad|Something urging a person to action",
"Gorge|Eat greedily/narrow opening with a stream",
"Gossamer|Soft light delicate material",
"Gouge|Tool for cutting grooves in wood",
"Grandiloquent|Using pompous words",
"Grave|Serious requiring consideration",
"Graze|Touch or scrape lightly in passing",
"Gregarious|Living in societies liking the company",
"Grievous|Causing grief or pain serious dire grave",
"Grovel|Crawl humble oneself",
"Guile|Deceit cunning",
"Gullible|Easily gulled",
"Gush|Burst out suddenly/talk ardently",
"Gust|Outburst of reeling sudden rain wind me etc.",
"Hack|Cut roughly hired horse",
"Halcyon|Calm and peaceful",
"Hallow|To whom it may concern: make holy consecrate",
"Harangue|A long passionate speech",
"Harbinger|Something or somebody that foretells the coming of",
"Harrow|To distress create stress or torment",
"Haughty|Arrogant conceited",
"Heed|Attention/give notice to",
"Heinous|Odious (of crime)",
"Heresy|Belief contrary to what is generally accepted",
"Hermetic|Sealed by fusion",
"Heterogeneous|Made up of different kinds",
"Hew|Make by hard work cut (by striking)",
"Highbrow|(Person) with superior tastes",
"Hirsute|Hairy shaggy",
"Hoax|Mischievous trick played on somebody for a joke",
"Hoi|Polloi the masses the rabble",
"Hollow|Not soled with hole",
"Holster|Leather case for a pistol",
"Homiletics|Act of preaching",
"Hone|Stone used for sharpening tools",
"Hoodwink|Trick mislead",
"Hospitable|Liking to give hospitality",
"Hubris|Arrogant pride",
"Hush|Make or become silent",
"Husk|Worthless outside part of anything",
"Hypocrisy|Falsely making oneself appear to be good",
"Iconoclast|Person who attacks popular beliefs",
"Idiosyncrasy|Personal mannerism",
"Idolatry|Excessive admiration of",
"Idyll|A carefree episode or experience",
"Ignoble|Dishonorable common undignified",
"Ignominious|Shameful dishonorable undignified disgraceful",
"Illicit|Unlawful forbidden",
"Imbroglio|Complicated and embarrassing situation",
"Immaculate|Pure faultless",
"Imminent|Likely to come or happen soon",
"Immutable|That cannot be changed",
"Impair|Worsen diminish in value",
"Impassive|Unmoved feeling no sign of passion",
"Impecunious|Having little or no money",
"Impede|Hinder get in the way of",
"Impediment|Something that hinders (e.g. stammer)",
"Impending|Imminent being about to happen expected",
"Imperative|Urgent essential",
"Imperious|Commanding haughty arrogant",
"Impermeable|That cannot be permeated",
"Imperturbable|Calm not capable of being excited.",
"Impervious|Not allowing to pass through (of materials)",
"Imperviousness|Haughty arrogant commanding",
"Impetuous|Having sudden energy impulsive thrusting ahead forceful",
"Impiety|Lack of reverence or dutifulness",
"Implacable|Incapable of being placated, unpleasable",
"Implicate|Show that somebody has a share",
"Implicit|Implied though not plainly expressed",
"Implosion|Collapse bursting inward",
"Importune|Beg urgently solicit (of a prostitute)",
"Imprecation|An invocation of evil a curse",
"Impromptu|Without preparation",
"Impudent|Rash, indiscreet",
"Impugned|Challenged to be doubted",
"Impute|To attribute to a cause or source ascribe",
"Inadvertent|Not paying proper attention",
"Inane|Silly senseless",
"Inasmuch|Since because",
"Incense|Make angry",
"Incessant|Often repeated continual",
"Inchoate|Not yet fully formed, rudimentary, elementary",
"Incipient|Beginning",
"Incise|Engrave make a cut in",
"Incite|Stir up rouse",
"Inclined|Directing the mind in a certain direction",
"Incongruous|Out of place not in harmony or agreement",
"Incorrigibility|Cannot be cured or corrected",
"Incredulous|Skeptical unwilling to believe",
"Inculcate|Fix firmly by repetition",
"Incumbents|Official duties",
"Incursion|A raid a sudden attack",
"Indefatigability|Not easily exhaustible tirelessness",
"Indelible|That cannot be rubbed out",
"Indigence|Poverty",
"Indigenous|Native",
"Indistinct|Not easily heard seen clearly marked",
"Indolence|Laziness",
"Indomitable|Not easily discouraged or subdued",
"Indulge|Gratify give way to satisfy allow oneself",
"Indulgent|Inclined to indulge",
"Ineffable|Too great to be described in words",
"Ineluctable|Certain inevitable",
"Inept|Unskillful said or done at the wrong time",
"Ineptitude|Quality of being unskillful",
"Inferno|Hell",
"Infuriate|Fill with fury or rage",
"Infuse|Put pour fill",
"Ingenuous|Naïve young artless frank honest sincere",
"Ingest|Take in by swallowing",
"Inimical|Harmful or friendly",
"Inimitable|Defying imitation unmatchable",
"Innocuous|Causing no harm",
"Inscrutable|Incapable of being discovered or understood",
"Insensible|Unconscious unresponsive unaffected",
"Insinuate|Suggest unpleasantly make a way for something gently",
"Insipid|Without taste or flavor",
"Insouciant|Unconcerned carefree",
"Insularity|Narrow-mindedness, isolated",
"Insurrection|Rising of people to open resistance to",
"Interdict|Prohibit forbid",
"Interim|As an installment",
"Intersperse|Place here and there",
"Intransigence|Unwillingness to compromise, stubbornness, intractability",
"Intransigent|Uncompromising",
"Intrepid|Fearless, brave, undaunted",
"Introspection|Examining one’s own thoughts and feelings",
"Inundate|Flood cover by overflowing",
"Inured|Accustomed to adapted",
"Invective|Abusive language, curses",
"Inveigh|To attack verbally denounce deprecate",
"Inveterate|Deep-rooted. long-established",
"Invincible|Too strong to be defeated",
"Involute|Complex",
"Irascible|Irritable easily angered",
"Irate|Angry",
"Ire|Anger",
"Irksome|Tiresome",
"Irresolute|Hesitating undecided",
"Irrevocable|Final and unalterable",
"Itinerate|To travel from place to place to peregrinate",
"Jabber|Talk excitedly, utter rapidly",
"Jibe|Gibe make fun of",
"Jocular|Meant as a joke",
"Judicious|Sound in judgment wise",
"Knit|Draw together unite firmly",
"Labyrinthine|To entangle the state of affairs",
"Lachrymose|Causing tears tearful",
"Lackluster|(of eyes) dull",
"Lament|Show/feel great sorrow",
"Lassitude|Weariness, tiredness",
"Latent|Present but not yet active, developed or visible",
"Laudatory|Expressing or giving praise",
"Lavish|Giving or producing freely liberally or generously",
"Legacy|Something handed down from ancestors",
"Levee|Formal reception/ embankment",
"Levity|Lack to seriousness",
"Libel|Statement that damages reputation",
"Liberality|Free giving generosity",
"Libertine|Immoral person",
"Lien|Legal claim until a debt on it is repaid",
"Limn|Paint portray",
"Limp|Lacking strength walking unevenly",
"Lionize|Treat as a famous person",
"Lithe|Bending twisting",
"Loll|Rest to sit or stand in a lazy way hang (dog's tongue)",
"Lope|Move along with long strides",
"Loquacious|Talkative garrulous",
"Lucubrate|Write in scholarly fashion",
"Luculent|Easily understood, lucid clear",
"Lugubrious|Mournful excessively sad",
"Lull|Become quiet or less active",
"Lumber|Move in a clumsy/noisy way",
"Luminary|Star light-giving body",
"Lurk|Be out of view, ready to attack",
"Lustrous|Being bright polished",
"Macabre|Gruesome suggesting death",
"Macerate|Make or become son by soaking in water",
"Machination|Plot scheme (esp. evil)",
"Maladroit|Tactless clumsy",
"Malapropism|Misuse to a word (for one that resembles it)",
"Malevolence|Wishing to do evil",
"Malign|Injurious speak ill of somebody tell lie",
"Malinger|To fake illness or injury in order to shirk a duty",
"Malleable|Yielding easily shaped moldable adapting",
"Manacle|Chains for the hands or feet",
"Massacre|Cruel killing of a large number of people",
"Matriculation|Be admitted enter a university as a student",
"Maudlin|Sentimental in a silly or tearful way",
"Maul|Hurt by rough handling",
"Maverick|Rebel, nonconformist",
"Mellifluous|Sweetly flowing",
"Mendacity|Dishonesty",
"Mendicant|A beggar",
"Mercurial|Quick changeable in character fleeting",
"Meretricious|Attractive on the surface but of little value",
"Mesmerize|Hypnotize",
"Meticulous|Giving great attention to details",
"Mettle|Quality of endurance or courage",
"Mettlesome|Courageous high-spirited",
"Middling|Fairly good but not very good",
"Minatory|Menacing threatening",
"Mince|Pronounce or speak affectedly euphemize",
"Misanthrope|Person who hates mankind",
"Mischievous|Harmful, causing mischief",
"Miser|Person who loves wealth and spends little",
"Misogynist|One who hates women/females",
"Moderation|Quality of being limited not extreme",
"Mollify|Make calmer or quieter",
"Molt|Moult lose hair feathers before new growing",
"Morbid|Diseased unhealthy (e.g. about ideas)",
"Morose|Ill-tempered unsocial",
"Muffler|Cloth worn round the neck/silencer",
"Multifarious|Varied motley greatly diversified",
"Mundane|Worldly as opposed to spiritual commonplace everyday",
"Myriad|Very great number",
"Nadir|Lowest weakest point",
"Nascent|Coming into existence emerging",
"Nebulous|Cloud-like hazy vague indistinct",
"Negligent|Taking too little care",
"Neophyte|Person who has been converted to a belief",
"Nexus|A connection tie or link",
"Nibble|Show some inclination to accept (an offer)",
"Noisome|Offensive disgusting (smell)",
"Nonchalant|Not having interest",
"Nonplused|Greatly surprised",
"Nostrum|A quack remedy an untested cure",
"Noxious|harmful",
"Nugatory|Trifling/worthless",
"Obdurate|Hardened and unrepenting, stubborn, inflexible",
"Obfuscate|To darken make obscure muddle",
"Oblivious|Unaware, having no memory",
"Obloquy|Abusively detractive language sharp criticism vituperation",
"Obsequious|Too eager to obey or serve",
"Obstreperous|Noisy loud",
"Obtain|To be established accepted or customary",
"Obtrusive|Projecting prominent undesirably noticeable",
"Obtuse|Blunt/stupid",
"Obviate|To make unnecessary get rid of",
"Occluded|Blocked up",
"Odious|Repulsive hateful",
"Odium|Contempt dislike aversion",
"Odor|Smell favor reputation",
"Officious|Too eager or ready to help offer advice",
"Ominous|Threatening",
"Onerous|Needing effort burdensome",
"Opaqueness|Dullness/not allowing light to pass through",
"Opprobrious|Showing scorn or reproach",
"Ossify|To turn to bone to settle rigidly into an idea",
"Ostensible|Seeming appearing as such professed",
"Ostentation|Display to obtain admiration or envy",
"Ostracism|Shut out from society refuse to meet talk",
"Overhaul|Examine thoroughly to learn about the condition",
"Overweening|Presumptuously arrogant overbearing immoderate being a jerk",
"Paean|Song of praise or triumph",
"Palate|Roof of the mouth sense of taste",
"Palatial|Magnificent",
"Palliate|Lessen the severity of",
"Palpability|Can be felt touched understood",
"Palpitate|Tremble beat rapidly and irregularly",
"Panegyric|Formal praise eulogy",
"Paradigm|A model example or pattern",
"Parenthesis|Sentence within another one something separated",
"Pariah|An outcast a rejected and despised person",
"Parsimonious|Too economical miserly",
"Partisan|One-sided committed to a party biased or prejudiced",
"Patron|Regular customer person who gives support",
"Paucity|Scarcity a lacking of",
"Peccadillo|Small sin small weakness in one's character",
"Pedantic|Bookish, showing off learning",
"Pedestrian|Commonplace, trite, unremarkable",
"Pellucid|Transparent, easy to understand",
"Penchant|Strong inclination a liking",
"Penitent|Feeling or showing regret",
"Penurious|Poor/stingy",
"Penury|Extreme poverty",
"Peregrination|Traveling about wandering",
"Peremptory|Urgent imperative unchallengeable ending debate",
"Perfidious|Treacherous faithless",
"Perfidy|Treachery breaking of faith",
"Perfunctory|Done as a duty without care",
"Perilous|Dangerous",
"Peripatetic|Wandering",
"Perish|Be destroyed decay",
"Perjury|Willful false statement unlawful act",
"Permeate|Spread into every part of",
"Pernicious|Harmful injurious",
"Perpetrate|Be guilty commit (a crime)",
"Personable|Pleasing in appearance attractive",
"Perspicacity|Quick judging and understanding",
"Pertain|Belong as a part have reference",
"Pest|Destructive thing or a person who is nuisance",
"Petrified|Taken away power (to think feel act)",
"Petrify|To make hard rocklike",
"Petrous|Like a rock hard stony",
"Petulant|Unreasonably impatient",
"Philistine|A smug ignorant person one who lacks knowledge",
"Phlegmatic|Calm sluggish temperament unemotional",
"Picaresque|Involving clever rogues or adventurers",
"Pied|Of mixed colors",
"Pinch|Be too tight take between the thumb and finger",
"Pine|Waste away through sorrow or illness",
"Pious|Dutiful to parents, devoted to religion",
"Piquant|Agreeably pungent stimulating",
"Pique|Hurt the pride or self-respect stir (curiosity)",
"Pitfall|Covered hole as a trap unsuspected danger",
"Pith|Essential part force soft liquid substance",
"Pivotal|Of great importance (others depend on it)",
"Placate|Soothe, pacify, calm",
"Plaintive|Mournful melancholy sorrowful",
"Plaque|Flat metal on a wall as a memorial",
"Platitude|A trite or banal statement unoriginality",
"Plea|Request",
"Plead|Address a court of law as an advocate",
"Plethora|Glut",
"Pliant|Pliable easily bent shaped or twisted",
"Plod|Continue doing something without resting",
"Pluck|Pull the feathers off pick (e.g. flowers)",
"Plumb|Get to the root of",
"Plummet|Fall plunge steeply",
"Plunge|Move quickly suddenly and with force",
"Poignant|Deeply moving keen",
"Poncho|Large piece of cloth",
"Ponderous|Heavy bulky dull",
"Portent|Omen marvelous threatening",
"Precarious|Uncertain risky dangerous",
"Precepts|Rules establishing standards of conduct",
"Preclude|Prevent make impossible",
"Precursory|Preliminary anticipating",
"Predilection|Special liking mental preference",
"Predominate|Have more power than others",
"Preen|Tidy/show self-satisfaction",
"Premature|Doing or happening something before the right time",
"Preponderance|Greatness in number strength weight",
"Presage|Warning sign",
"Presumption|Arrogance",
"Preternatural|Not normal or usual",
"Prevalent|Common",
"Prevaricate|To equivocate to stray from the truth",
"Prim|Neat, formal",
"Pristine|Primitive unspoiled pure as in earlier times unadulterated",
"Probity|Uprightness incorruptibility principle",
"Proclivity|Inclination",
"Procrastination|Keeping on putting off",
"Prodigal|Wasteful reckless with money",
"Prodigious|Enormous wonderful",
"Profane|Worldly having contempt for god",
"Profligacy|Shameless immorality",
"Profligate|Wasteful prodigal licentious extravagant",
"Profundity|Depth",
"Profuse|Abundant/lavish",
"Proliferate|Grow/reproduce by rapid multification",
"Prolix|Tiring because too long",
"Prone|Prostrate inclined to (undesirable things)",
"Propagation|Increasing the number spreading extending",
"Propinquity|Nearness in time or place affinity of nature",
"Propitiatory|Conciliatory appeasing mitigating",
"Propitious|Auspicious presenting favorable circumstances",
"Prosaic|Everyday mundane commonplace trite pedestrian",
"Proscribe|Denounce as dangerous",
"Protracted|Prolonged",
"Provident|Frugal looking to the future",
"Provisional|Of the present time only",
"Provoke|Make angry, vex",
"Prudence|Careful forethought",
"Prudish|Easily shocked, excessively modest",
"Prune|Dried plum silly person",
"Pry|Get something inquire too curiously",
"Pucker|Wrinkle",
"Pugnacious|Fond of in the habit of fighting",
"Puissance|Strength",
"Punctilious|Precise paying attention to trivialities",
"Pundit|Pedant authority on a subject",
"Pungency|Sharpness stinging quality",
"Purvey|Provide supply",
"Pusillanimous|Cowardly craven",
"Putrefaction|Becoming rotten",
"Pyre|Large pile of wood for burning",
"Quack|Person dishonestly claiming to something",
"Quaff|Drink deeply",
"Quail|Lose courage turn frightened",
"Qualm|Feeling of doubt temporary feeling of sickness",
"Quandary|State of doubt or perplexity",
"Quell|Suppress subdue",
"Quibble|Try to avoid by sophistication",
"Quiescence|State of being passive/motionless",
"Quiescent|At rest, dormant, torpid",
"Quirk|Habit or action peculiar to somebody or something",
"Quixotic|Generous unselfish",
"Quotidian|Banal everyday",
"Rabble|Mob crowd the lower classes of populace",
"Raconteur|Person who tells anecdotes",
"Raffish|Low vulgar base tawdry",
"Ramify|To be divided or subdivided to branch out",
"Rancorous|Feeling bitterness spitefulness",
"Rant|Use extravagant language",
"Rapacious|Greedy (esp. for money)",
"Rarefy|To make thin to make less dense to purify or refine",
"Rave|Act with excessive enthusiasm",
"Reactionary|Opposing progress",
"Rebuff|Snub",
"Recalcitrant|Disobedient",
"Recant|Take back as being false give up",
"Recast|Cast or fashion anew",
"Recidivism|Relapse into antisocial or criminal behavior",
"Reciprocity|Granting of privileges in return for similar",
"Recitals|A number of performance of music",
"Recluse|Person who lives alone and avoids people",
"Recompense|Make payment to reward punish",
"Reconcile|Settle a quarrel restore peace",
"Recondite|Little known abstruse",
"Recreancy|Cowardice a cowardly giving up",
"Recuperate|Become strong after illness loss exhaustion",
"Redeem|Get back by payment compensate",
"Redoubtable|Formidable causing fear",
"Refine|Make or become pure cultural",
"Refractory|Stubborn, unmanageable, untractable",
"Refulgent|Shining brilliant",
"Regale|To delight or entertain to feast",
"Regicide|Crime of killing a king",
"Reiterate|Say or do again several times",
"Rejuvenation|Becoming young in nature or appearance",
"Relapse|Fall back again",
"Remonstrate|To protest, object",
"Render|Deliver/provide/represent",
"Renovate|Restore something to better condition",
"Renowned|Celebrated, famous",
"Repast|Meal",
"Repel|Refuse to accept/cause dislike",
"Repine|At be discontented with",
"Reproach|Scold upbraid",
"Reprobate|Person hardened in sin one devoid of decency",
"Repudiate|Disown refuse to accept or pay",
"Repulsive|Causing a feeling of disgust",
"Requite|Repay give in return",
"Rescind|Repeal/annul/cancel",
"Resigned|Unresisting submissive",
"Resilience|Quality of quickly recovering the original shape",
"Resort|To frequently visit",
"Restive|Refusing to move reluctant to be controlled",
"Resuscitation|Coming back to consciousness",
"Retard|Check hinder",
"Reticent|Reserved, not talkative, silent/taciturn",
"Revere|Have deep respect for",
"Reverent|Feeling or showing deep respect",
"Riddle|Puzzling person or thing",
"Rift|Split crack dissension",
"Rivet|Fix take up secure metal pin",
"Roll Call|calling of names",
"Rotund|Rich and deep plump and round",
"Ruffian|Violent cruel man",
"Rumple|Make rough",
"Sagacious|Having sound judgment perceptive wise like a sage",
"Salacious|Obscene",
"Salubrious|Healthful",
"Salutary|Remedial wholesome causing improvement",
"Sanctimony|Self-righteousness hypocritical with false piety",
"Sanction|Approval (by authority) penalty",
"Sanguine|Cheerful confident optimistic",
"Sanity|Health of mind soundness of judgement",
"Sash|Long strip worn round the waist",
"Satiate|Satisfy fully",
"Saturnine|Gloomy/dark/sullen/morose",
"Savant|Person of great learning",
"Savor|Taste something",
"Sawdust|Tiny bits of wood",
"Scabbard|Sheath for the blade",
"Scent|Smell (esp. pleasant)",
"Scorch|Become discolored/dry up/go at high speed",
"Scribble|Write hastily",
"Scurvy|Mean/contemptible",
"Secular|Material (not spiritual) living outside monasteries",
"Sedulous|Persevering",
"Seminal|Like a seed constituting a source originative",
"Sententious|Snort and pithy full of maxims/proverbs",
"Sequence|Succession connected line of",
"Sere|Make hard and without feeling",
"Sermon|Reproving a person for his faults",
"Serrated|Having a toothed edge",
"Serration|Having a toothed edge",
"Servile|Like a slave lacking independence",
"Sever|Break off",
"Severance|Severing",
"Shallow|Little depth not earnest",
"Shard|Piece of broken earthenware",
"Sheath|Cover for the blade of a weapon or a tool",
"Shrewd|Astute showing sound judgement",
"Shrill|Sharp piercing",
"Shun|Keep away from avoid",
"Shunt|Send from one track to another lay aside evade discussion",
"Sidestep|Step to one side",
"Simper|(Give a) silly/self-conscious smile",
"Sinuous|Winding undulating serpentine",
"Skiff|Small boat",
"Skit|Short piece of humorous writing",
"Slack|Sluggish dull not tight",
"Slake|To assuage to satisfy allay",
"Slate|King of blue-grey stone propose criticize",
"Sluggard|Lazy slow-moving person",
"Slur|Join sounds/words (indistinct)",
"Smolder|Burn slowly without flame",
"Snare|Trap",
"Snub|Treat with contempt",
"Soar|Rise fly high",
"Sober|Self-controlled",
"Sobriety|Quality or condition of being sober",
"Sodden|Soaked saturated",
"Soggy|Heavy with water",
"Solvent|Of the power of forming a solution",
"Somatic|Of the body",
"Soot|Black powder in smoke",
"Sophisticated|Complex subtle refined",
"Sophistry|Fallacious reasoning faulty logic",
"Sophomoric|Self-assured though immature affected bombastic overblown",
"Soporific|Producing sleep",
"Sordid|Wretched comfortless contemptible",
"Spear|Weapon with a metal point on a long shaft",
"Specious|Illogical of questionable truth or merit",
"Splenetic|Bad-tempered irritable",
"Splice|Join (two ends)",
"Sponge|Porous rubber for washing",
"Spurious|False counterfeit",
"Spurn|Have nothing to do reject or refuse",
"Squalid|Foul filthy",
"Squander|Spend wastefully",
"Squat|Crouch/settle without permission",
"Stanch|To stop the flow of a fluid",
"Steeply|Rising or failing sharply",
"Stentorian|Extremely loud and powerful",
"Stickler|Person who insists on importance of something",
"Stigma|Mark of shame or disgrace",
"Stigmatize|Describe somebody scornfully",
"Sting|Something sharp",
"Stingy|Spending using unwillingly",
"Stint|To be thrifty to set limits",
"Stipple|Paint with dots",
"Stipulate|State or put forward as a necessary condition",
"Stolid|Showing no emotion impassive'",
"Stray|Wander lose one's way",
"Streak|Long thin move very fast",
"Striated|Striped grooved or banded",
"Stride|Walk with long steps",
"Strut|A supporting bar",
"Stygian|Hence dark gloomy",
"Stymie|To hinder obstruct or block",
"Subdue|Overcome bring under control",
"Sublime|Extreme astounding",
"Submerge|Put under water liquid sink out of sight",
"Suborn|Induce by bribery or something to commit perjury",
"Subpoena|Written order requiring a person to appear in a low court",
"Substantiation|Giving facts to support (statement)",
"Subsume|Include under a rule",
"Succor|Assistance relief in time of distress",
"Suffice|Be enough",
"Suffocate|Cause or have difficulty in breathing",
"Sullied|To be stained or discredited",
"Summarily|Briefly without delay",
"Sumptuous|Magnificent",
"Sundry|Various miscellaneous separate",
"Supercilious|Disdainful characterized by haughty scorn",
"Superfluous|More than is needed or wanted",
"Superimpose|Put something on the top",
"Supersede|Take the place of",
"Supine|Lying on the back slow to act passive",
"Suppliant|Asking humbly beseeching",
"Supplicate|Make a humble petition to",
"Suppress|Prevent from being known put an end to",
"Surcharge|Additional load/charge",
"Surfeit|Satiate fee to fullness or to excess",
"Susceptibility|Sensitiveness",
"Swerve|Change direction suddenly",
"Sycophant|Person who flatter to the rich and powerful",
"Synopsis|Summary or outline",
"Taciturn|Not talkative, silent",
"Tadpole|Form of a frog when it leaves the egg",
"Talon|Claw of a bird of prey",
"Tamp|Tap or drive down by repeated light blows",
"Tamper|Interfere with",
"Tangential|Suddenly changeable",
"Tarnished|Lost brightness",
"Tassel|Bunch of threads",
"Taunt|Contemptuous reproach hurtful remark",
"Taut|Tightly stretched",
"Tautology|A repetition a redundancy",
"Tawdry|Cheap gaudy showy tacky",
"Teetotal|Oppose to alcohol",
"Temerity|Boldness brashness intrepidness",
"Temperance|Abstinence from alcohol self-control moderation",
"Temperate|Showing self-control",
"Tenacity|Firmness persistency adhesiveness tending to hang on",
"Tenuous|Insubstantial flimsy weak",
"Tepid|Lukewarm",
"Terse|Brief and to the point",
"Testiness|Witness/evidence",
"Thrift|Care economy thriving prosperous",
"Thwart|Obstruct/frustrate",
"Timid|Shy easily frightened",
"Timorous|Fearful timid afraid",
"Toady|Obsequious flatterer",
"Tonic|Something giving strength or energy",
"Topple|Be unsteady and overturn",
"Torment|Severe pain or suffering",
"Torpid|Sleeping sluggish lethargic dormant",
"Torque|Twisting force causing rotation",
"Tortuous|Devious/not straightforward",
"Tout|Person who worries others to buy something to use his service",
"Tractable|Easily controlled or guided",
"Transgress|Break go beyond (a limit)",
"Transient|Temporary fleeting",
"Transitory|Brief",
"Travesty|Parody/imitation",
"Trenchant|Forceful effective vigorous extremely perceptive incisive",
"Trepidation|Alarm excited state of mind",
"Trickle|Flow in drops",
"Trifling|Unimportant",
"Trite|Not new",
"Truce|(Agreement) stop of fighting for a time",
"Truculence|Aggressiveness ferocity",
"Trudge|Walk heavily",
"Turbid|Muddy having the sediment stirred up",
"Turbulence|Being uncontrolled violent",
"Turgid|Excessively ornate swollen or bloated",
"Turmoil|Trouble disturbance",
"Turpitude|Wickedness shamefulness",
"Turquoise|Greenish-blue precious stone",
"Tyro|A beginner, novice",
"Ubiquitous|Present everywhere",
"Ulterior|Situated beyond",
"Umbrage|Offense resentment",
"Uncouth|Rough awkward",
"Underbid|Make a lower bid then somebody else",
"Undermine|Weaken gradually at the base make something under",
"Undulate|To move in wavelike fashion fluctuate",
"Unearth|Discover and bring to light",
"Unencumbered|Easy-going trifle",
"Unfeigned|Not pretended, sincere",
"Unscathed|Unharmed, unhurt",
"Untoward|Unfortunate inconvenient",
"Upbraid|Scold, reproach",
"Urbane|Elegant refined In manners",
"Vacillation|Being uncertain, indecision",
"Vagary|Strange act or idea",
"Vain|Without use, result conceited",
"Valiant|Brave",
"Valorous|Brave",
"Vanquish|Conquer",
"Veer|Change direction",
"Venal|Ready to do something dishonest",
"Veneer|Surface appearance covering the TRUE nature",
"Veneration|Regard with deep respect",
"Veracity|Truth",
"Verdant|Fresh and green",
"Verisimilitude|Appearing true or real",
"Veritable|Real rightly named",
"Verve|Spirit vigor enthusiasm",
"Vestige|Trace or sign",
"Vex|Annoy/distress/trouble",
"Vigilance|Watchfulness self-appointed group who maintain order",
"Vigilant|Member of a vigilance committee",
"Vigorous|Strong, energetic",
"Vilify|Slander, say evil things",
"Vindictive|Having a desire to revenge",
"Virago|A loud domineering woman a scold or nag",
"Visceral|Of the internal organs of the body",
"Viscous|Sticky/semi-fluid",
"Vitiate|Lower the quality weaken the strength",
"Vituperate|Curse abuse in words",
"Vivacious|Lively high-spirited",
"Volatile|Changeable inconstant fickle unstable explosive",
"Volubility|Fluency verbosity easy use of spoken language",
"Voluble|Fluent",
"Waffle|Talk vaguely and without much result",
"Waft|Scent waving movement carry lightly through",
"Wag|Merry person",
"Warmonger|Person who stirs up war",
"Warrant|Authority, written order, guarantee",
"Wean|To turn away (from a habit)",
"Weigh|Measure the heaviness of something",
"Welter|Turmoil, a bewildering jumble",
"Wend|To go proceed",
"Whimsical|Full of odd and fanciful ideas",
"Wince|Show bodily or mental pain",
"Woo|Try to win",
"Writ|Written order",
"Yam|Tale story fibers for knitting"
];

// Rehydrate data structure
const rawData: Omit<Word, 'id' | 'category'>[] = compressedData.map(line => {
    const [term, meaning] = line.split('|');
    return { term, meaning };
});

// --- Semantic Categorization Logic ---

const getCategoryForWord = (term: string, meaning: string): string => {
  const m = meaning.toLowerCase();
  const t = term.toLowerCase();
  const text = `${t} ${m}`;

  // Conflict & Hostility
  if (text.match(/hate|dislike|enemy|war|fight|attack|hostile|angry|rage|scold|punish|blame|critic|argue|quarrel|resent|offen|vulgar|cruel|violent|kill|harm|destroy|damage|force|rebel|oppose|danger/)) return "Conflict & Hostility";
  
  // Money & Wealth
  if (text.match(/money|wealth|pay|cost|debt|rich|poor|cheap|value|price|buy|sell|bank|fund|greedy|miser|economic|profit|loss|business|trade/)) return "Money & Wealth";
  
  // Emotions & Attitudes (Positive)
  if (text.match(/happy|joy|eager|cheer|please|kind|friend|love|like|approv|praise|respect|calm|peace|polite|humor|laugh|faith|hope|good|truth|loyal/)) return "Positive Emotions";
  
  // Emotions & Attitudes (Negative/Sad)
  if (text.match(/sad|grief|sorrow|mourn|fear|afraid|anxiet|worry|doubt|confuse|puzzle|regret|shame|guilt|embarrass|bad|evil|worse/)) return "Negative Emotions";
  
  // Speech & Communication
  if (text.match(/speak|talk|say|speech|language|word|write|letter|announce|declare|silent|quiet|ask|answer|argument|discuss|meaning|deny/)) return "Communication";
  
  // Law, Truth & Deception
  if (text.match(/law|judge|court|crime|legal|truth|lie|false|fake|cheat|deceive|honest|guilt|innocent|rule|govern|prison/)) return "Law, Truth & Deception";
  
  // Physical Properties
  if (text.match(/big|small|large|tiny|heavy|light|shape|color|bright|dark|hard|soft|hot|cold|move|fast|slow|break|bend|water|liquid|solid|air|fire/)) return "Physical Properties";
  
  // Mind & Knowledge
  if (text.match(/think|mind|know|learn|study|idea|stupid|clever|wise|skill|understan|teach|book|belief/)) return "Mind & Knowledge";
  
  // Time & Change
  if (text.match(/time|old|new|future|past|change|begin|end|stop|start|continue|remain/)) return "Time & Change";

  return "General Vocabulary";
};

// --- Grouping Logic ---

export const getGroupedData = (groupSize: number = 30): WordGroup[] => {
  // 1. Assign Categories
  const categorizedWords = rawData.map((item, index) => ({
    ...item,
    id: `word_${index}`,
    category: getCategoryForWord(item.term, item.meaning),
  }));

  // 2. Group by Category
  const categoryMap: Record<string, Word[]> = {};
  categorizedWords.forEach(word => {
    if (!categoryMap[word.category!]) {
      categoryMap[word.category!] = [];
    }
    categoryMap[word.category!].push(word);
  });

  const groups: WordGroup[] = [];
  
  // 3. Create Groups from Categories
  Object.keys(categoryMap).sort().forEach((catName, idx) => {
    const wordsInCat = categoryMap[catName];
    
    // If a category is too huge, chunk it
    const chunkSize = 40;
    if (wordsInCat.length > chunkSize) {
       for (let i = 0; i < wordsInCat.length; i += chunkSize) {
         groups.push({
           id: `${catName}_${i}`,
           label: `${catName} ${Math.floor(i/chunkSize) + 1}`,
           words: wordsInCat.slice(i, i + chunkSize),
         });
       }
    } else {
       groups.push({
         id: `cat_${idx}`,
         label: catName,
         words: wordsInCat,
       });
    }
  });

  // Ensure "General Vocabulary" is last
  const generalGroups = groups.filter(g => g.label.startsWith("General Vocabulary"));
  const otherGroups = groups.filter(g => !g.label.startsWith("General Vocabulary"));
  return [...otherGroups, ...generalGroups];
};

// Flattened data for random access
export const allWords: Word[] = rawData.map((item, index) => ({
    ...item,
    id: `word_${index}`,
    category: getCategoryForWord(item.term, item.meaning),
}));
